# Site settings
title: The Rust Community Blog
description: >
  Words from the Rust Community team and guests
baseurl: ""
url: "http://blog.community.rs"
logo: "https://www.rust-lang.org/logos/rust-logo-64x64-blk.png"
twitter_username: rustlang
github_username:  rust-community

# Build settings
highlighter: rouge

root: http://blog.community.rs
